import { Submarine } from "@/types/submarines.types"

export const submarines: Submarine[] = [
   {
      name: "TYPE IIC",
      preview: "/images/type2c.png",
      images: ["/images/u-23wb.jpg", "/images/blueprint-2c.png"],
      description: "Small coastal U-boat designed for short-range patrols and training missions.",
      content: {
         Torpedoes: "5",
         "Torpedo Tubes": "3 bow tubes",
         Length: "43.9 m",
         Range: "3,800 nautical miles at 8 knots",
         "Underwater Range": "42 nautical miles at 4 knots",
         "Max Surface Speed": "12 knots",
         "Max Underwater Speed": "7 knots",
         Crew: "22-24",
         "Max Diving Depth": "150 m",
         "Main Role": "Coastal patrol and short-range attacks",
      },
   },
   {
      name: "TYPE VIIC",
      preview: "/images/type7c.png",
      images: [
         "/images/blueprint-7c-1.png",
         "/images/blueprint-7c-2.png",
         "/images/blueprint-7c-3.png",
         "/images/blueprint-7c-4.png",
      ],
      description: "The main combat U-boat of the Kriegsmarine, used extensively in the Battle of the Atlantic.",
      content: {
         Torpedoes: "14",
         "Torpedo Tubes": "4 bow tubes, 1 stern tube",
         Length: "67.1 m",
         Range: "8,500 nautical miles at 10 knots",
         "Underwater Range": "80 nautical miles at 4 knots",
         "Max Surface Speed": "17.7 knots",
         "Max Underwater Speed": "7.6 knots",
         Crew: "44-52",
         "Max Diving Depth": "220 m",
         "Main Role": "Long-range Atlantic warfare and convoy attacks",
      },
   },
   {
      name: "TYPE VIIC/42",
      preview: "/images/type7c42.png",
      images: ["/images/7c42-1.png", "/images/7c42-2.png"],
      description:
         "An improved VIIC design with stronger hull protection and better survivability, though never completed.",
      content: {
         Torpedoes: "16",
         "Torpedo Tubes": "4 bow tubes, 1 stern tube",
         Length: "68.7 m",
         Range: "12,600 nautical miles at 10 knots",
         "Underwater Range": "80 nautical miles at 4 knots",
         "Max Surface Speed": "18.6 knots",
         "Max Underwater Speed": "7.6 knots",
         Crew: "44-52",
         "Max Diving Depth": "270 m",
         "Main Role": "Improved Atlantic combat and deep-diving operations",
      },
   },
   {
      name: "TYPE XXI",
      preview: "/images/type21.png",
      images: ["/images/blueprint-21-1.png", "/images/blueprint-21-2.png"],
      description: "A revolutionary electro-boat designed for high underwater speed and long submerged operations.",
      content: {
         Torpedoes: "23",
         "Torpedo Tubes": "6 bow tubes",
         Length: "76.7 m",
         Range: "15,500 nautical miles at 10 knots",
         "Underwater Range": "340 nautical miles at 5 knots",
         "Max Surface Speed": "15.6 knots",
         "Max Underwater Speed": "17.2 knots",
         Crew: "57-60",
         "Max Diving Depth": "280 m",
         "Main Role": "High-speed underwater warfare and stealth operations",
      },
   },
]
